version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels :
      - "type/dependencies"

  - package-ecosystem: "github-actions"
    directory: "deploy"
    schedule:
      interval: "daily"
    labels :
      - "type/dependencies"

  - package-ecosystem: "github-actions"
    directory: "notification"
    schedule:
      interval: "daily"
    labels :
      - "type/dependencies"
