name: Lint

on:
  pull_request:
    paths:
      - '**/*.yml'
  workflow_dispatch:

jobs:
  actionlint:
    name: Actions

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.1

      - uses: reviewdog/action-actionlint@v1
