name: Auto rebase

on:
  workflow_call:
    inputs:
      bot:
        default: starfire-bot
        description: The bot to use for the rebase.
        type: string
        required: false
    secrets:
      GH_TOKEN:
        description: 'Personal access token passed from the caller workflow'
        required: true
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  token: ${{ secrets.GH_TOKEN }}

jobs:
  rebase:
    name: Rebase

    runs-on: ubuntu-latest

    if: github.event.issue.pull_request != '' && toJson(github.event.comment.body) == '"@${{ inputs.bot }} rebase"'

    steps:
      - name: debug
        if: toJson(github.event.comment.body) == "@${{ inputs.bot }} rebase"
        run: |
          echo "let's run ${{ toJson(github.event.comment.body) }}"
      - name: React to comment
        uses: dkershner6/reaction-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          commentId: ${{ github.event.comment.id }}
          reaction: "+1" # Optional, defaults to +1

      - name: Checkout the latest code
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

      - name: Check issue state
        if: github.event.issue.state != 'open' || github.event.issue.locked == true || github.event.issue.draft == true
        run: |
          gh run cancel ${{ github.run_id }}
          echo "::warning:: Rebase requested by ${{ github.event.comment.user.login }}, but issue state is not open or issue is locked or draft"

      - name: Automatic Rebase
        if: github.event.issue.state == 'open' && github.event.issue.locked == false && github.event.issue.draft == false
        uses: cirrus-actions/rebase@1.7

      - name: Comment
        if: github.event.comment.user.login != ${{ inputs.bot }}
        run: |
          gh pr comment ${{ github.event.issue.number }} --body "Complete."
          echo "::notice:: Rebase requested by ${{ inputs.bot }}, rebase complete."
