name: Dependabot auto merge

on:
  workflow_call:
    inputs:
      target:
        description: The target branch to merge into.
        type: string
        required: false
        default: patch
      command:
        description: The command to run.
        type: string
        required: false
        default: squash and merge
      botName:
        description: The name of the bot.
        type: string
        required: false
        default: starfire-bot
    secrets:
      GH_TOKEN:
        description: 'Personal access token passed from the caller workflow'
        required: true

jobs:
  auto-merge:
    name: Dependabot
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }} && toJson(github.event.comment.body) == '"@${{ inputs.botName }} ${{ inputs.command }}"'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        id: dependabot-auto-merge
        with:
          target: ${{ inputs.target }}
          command: ${{ inputs.command }}
          github-token: ${{ secrets.GH_TOKEN }}
          botName: ${{ inputs.botName }}

      - name: Use GH for merge PR
        if: success()
        run: |
          gh pr merge ${{ github.event.number }} --squash -d
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
