name: Deployment

on:
  workflow_call:
    inputs:
      registry:
        default: xnxktech.tencentcloudcr.com
        type: string
        required: false
      environment:
        default: Production
        description: The environment to use for the Production.
        type: string
        required: false
      environment_url:
        default: https://prod.example.com
        description: The URL to use for the Production.
        type: string
        required: false
    secrets:
      K8S_CONFIG:
        required: true

jobs:
  deploy:
    name: Argo
    if: ${{ github.event_name != 'pull_request' }}
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment_url }}
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ inputs.environment }}
      cancel-in-progress: false

    steps:
      - name: Split Version or Branch
        uses: jungwinter/split@v2
        id: split
        with:
          separator: '/'
          msg: ${{ github.ref }}

      - name: Checkout ${{ steps.split.outputs._2 }}
        uses: actions/checkout@v4.0.0
        with:
          ref: ${{ steps.split.outputs._2 }}

      - name: Setup repo name to lowercase
        id: reponame
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Split repo name
        uses: jungwinter/split@v2
        id: split_reponame
        with:
          separator: '/'
          msg: ${{ steps.reponame.outputs.lowercase }}

      - name: Set new version to Argo rollouts
        uses: starubiquitous/kubectl-argo-rollouts@main
        env:
          KUBE_CONFIG: ${{ secrets.K8S_CONFIG }}
        with:
          args: set image ${{ steps.split_reponame.outputs._1 }} ${{ steps.split_reponame.outputs._1 }}=${{ inputs.registry }}/${{ steps.reponame.outputs.lowercase }}:${{ steps.split.outputs._2 }} --insecure-skip-tls-verify
