name: Laravel Tests with Pest

on:
  workflow_call:
    inputs:
      versions:
        description: 'Stringified JSON object listing target PHP versions'
        default: '[\"8.0\"]'
        required: true
        type: string
      stability:
        default: '[\"prefer-stable\"]'
        required: true
        type: string

jobs:
  ci:
    name: ${{ matrix.php-versions }} - ${{ matrix.stability }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ${{fromJson(inputs.versions)}}
        stability: ${{fromJson(inputs.stability)}}
    services:
      database:
        image: postgres:12.4-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, memcached, gmp
          coverage: xdebug
          tools: php-cs-fixer, phpunit, composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2.1.7
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Set Minimum PHP 8.0 Versions
        uses: nick-invision/retry@v2.6.0
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require guzzlehttp/guzzle:^7.2 --no-interaction --no-update
        if: matrix.php-versions >= 8

      - name: Set Minimum PHP 8.1 Versions
        uses: nick-invision/retry@v2.6.0
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require symfony/symfony:5.4.x-dev league/commonmark:^2.0.2 phpunit/phpunit:^9.5.8 --no-interaction --no-update
        if: matrix.php-versions >= 8.1

      - name: Install dependencies
        uses: nick-invision/retry@v2.6.0
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Prepare Laravel Application
        run: |
          cp .env.testing .env
          php artisan key:generate --ansi
          php artisan config:cache
          php artisan migrate
          php artisan db:seed
          php artisan api:cache
          php artisan config:cache

      - name: Run Testsuite
        run: vendor/bin/pest tests/ --coverage-text --colors=always --coverage-html=coverage
