name: Laravel Tests with Pest

on:
  workflow_call:
    inputs:
      versions:
        description: 'Stringified JSON object listing target PHP versions'
        default: "['8.0']"
        required: false
        type: string
      stability:
        default: "['prefer-stable']"
        required: false
        type: string
      fail-fast:
        default: true
        description: "Whether to fail fast or not"
        required: false
        type: boolean
      command:
        description: 'Command to prepare Laravel Application'
        default: |
          cp .env.testing .env
          php artisan key:generate --ansi
          php artisan config:cache
        required: false
        type: string
      jwt:
        description: 'Stringified JSON object listing JWT keys'
        default: false
        required: false
        type: boolean
      need_env:
        description: 'Stringified JSON object listing environment variables'
        default: false
        required: false
        type: boolean
      database:
        description: 'Database to use for testing'
        default: 'postgres:12.4-alpine'
        required: false
        type: string
      db_user:
        description: 'Database user to use for testing'
        default: 'postgres'
        required: false
        type: string
      redis:
        description: 'Redis to use for testing'
        default: 'redis:5.0-alpine'
        required: false
        type: string
      extensions:
        description: 'List of PHP extensions to install'
        default: 'dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, memcached, gmp'
        required: false
        type: string
      coverage:
        description: 'Enable PHP code coverage'
        default: 'xdebug'
        required: false
        type: string
      tools:
        description: 'List of tools to install'
        default: 'php-cs-fixer, phpunit'
        required: false
        type: string
      composer_version:
        description: 'Version of Composer to use'
        default: 'v2'
        required: false
        type: string
      cache-key:
        description: 'Cache key to use for caching'
        default: 'cache-v1'
        required: false
        type: string
      pest_command:
        description: 'Command to run Pest'
        default: '--coverage-text --colors=always --coverage-html=coverage --coverage-clover coverage.xml'
        required: false
        type: string
      codecov:
        description: 'Enable CodeCov'
        default: false
        required: false
        type: boolean
    secrets:
      codecov_token:
        required: false

jobs:
  ci:
    name: ${{ matrix.php-versions }} - ${{ matrix.stability }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ${{fromJson(inputs.versions)}}
        stability: ${{fromJson(inputs.stability)}}
    services:
      database:
        image: ${{ inputs.database }}
        env:
          POSTGRES_DB: ${{ inputs.db_user }}
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
      redis:
        image: ${{ inputs.redis }}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 1

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ inputs.extensions }}
          key: ${{ inputs.cache-key }}

      - name: Cache extensions
        uses: actions/cache@v3.0.11
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ inputs.extensions }}
          coverage: ${{ inputs.coverage }}
          tools: ${{ inputs.tools }}, composer:${{ inputs.composer_version }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3.0.11
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Set Minimum PHP 8.0 Versions
        uses: nick-invision/retry@v2.8.2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require guzzlehttp/guzzle:^7.2 --no-interaction --no-update
        if: matrix.php-versions >= 8

      - name: Set Minimum PHP 8.1 Versions
        uses: nick-invision/retry@v2.8.2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require symfony/symfony:5.4.x-dev league/commonmark:^2.0.2 phpunit/phpunit:^9.5.8 --no-interaction --no-update
        if: matrix.php-versions >= 8.1

      - name: Install dependencies
        uses: nick-invision/retry@v2.8.2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Prepare JWT keys
        if: ${{ inputs.jwt }}
        run: yes 2>/dev/null | php artisan jwt:secret

      - name: Prepare Laravel Application
        run: ${{ inputs.command }}

      - name: Prepare JWT keys
        if: ${{ inputs.jwt }}
        run: yes 2>/dev/null | php artisan jwt:secret

      - name: Look up .env file
        if: ${{ inputs.need_env }}
        run: cat .env

      - name: Run Testsuite
        run: XDEBUG_MODE=coverage vendor/bin/pest tests/ ${{ inputs.pest_command }}

      - name: Upload coverage to Codecov
        if: ${{ inputs.coverage }}
        uses: codecov/codecov-action@v3
        with:
            token: ${{ secrets.codecov_token }}
