name: Node Eslint

on:
  workflow_call:
    inputs:
      versions:
        description: 'Stringified JSON object listing target Node versions'
        default: "[\"16\"]"
        required: false
        type: string

jobs:
  build:

    name: ${{ matrix.node-versions }} Eslint

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: ${{fromJson(inputs.versions)}}

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node }}

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - uses: actions/cache@v3.0.3
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - name: Install package.json dependencies with Yarn
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true

      - name: Check with eslint
        uses: tinovyatkin/action-eslint@v1
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          check-name: eslint
