name: Prettier

on:
  workflow_call:
    inputs:
      versions:
        description: 'Stringified JSON object listing target Node versions'
        default: "[\"16\"]"
        required: false
        type: string
      reviewers:
        description: 'Stringified JSON object listing target reviewers'
        default: "[\"XNXKTech/infra\"]"
        required: false
        type: string
      labels:
        description: 'Stringified JSON object listing target labels'
        default: |
          status/needs-review
        required: false
        type: string

jobs:
  build:

    name: Prettier

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: ${{fromJson(inputs.versions)}}

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node }}

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - uses: actions/cache@v3.0.3
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - name: Install package.json dependencies with Yarn
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true

      - name: Prettier fix
        run: yarn lint --fix

      - name: Create Pull Request
        if: ${{ always() }}
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.CI_PAT }}
          commit-message: "style: fix typo"
          title: "style: fix typo"
          branch-suffix: short-commit-hash
          branch: style-fix-typo
          reviewers: ${{ inputs.reviewers }}
          labels: ${{ inputs.labels }}
          delete-branch: true
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
