name: Prettier

on:
  workflow_call:
    inputs:
      runs-on:
        default: "['ubuntu-latest']"
        description: The OSs that the workflow is run on
        required: false
        type: string
      versions:
        description: 'Stringified JSON object listing target Node versions'
        default: "['16']"
        required: false
        type: string
      reviewers:
        description: 'Stringified JSON object listing target reviewers'
        default: "['XNXKTech/infra']"
        required: false
        type: string
      labels:
        description: 'Stringified JSON object listing target labels'
        default: |
          status/needs-review
        required: false
        type: string
    secrets:
      GH_TOKEN:
        description: 'Personal access token passed from the caller workflow'
        required: false

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN == '' && secrets.GITHUB_TOKEN || secrets.GH_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN == '' && secrets.GITHUB_TOKEN || secrets.GH_TOKEN }}
  token: ${{ secrets.GH_TOKEN == '' && secrets.GITHUB_TOKEN || secrets.GH_TOKEN }}

jobs:
  prettier:

    name: Prettier

    if: ${{ github.actor != 'dependabot[bot]' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ${{ fromJson(inputs.runs-on) }}
        node-versions: ${{ fromJson(inputs.versions) }}

    steps:
      - name: Environment
        run: env | sort

      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node }}

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - uses: actions/cache@v3.0.8
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - name: Install package.json dependencies with Yarn
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --ignore-engines --ignore-optional
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true

      - name: Prettier
        run: npx prettier --write '**/*.{js,jsx,ts,tsx}'

      - name: Starfire bot
        if: contains(fromJson('["XNXKTech", "StarUbiquitous"]'), github.event.repository.owner.name) == true
        run: |
          git config user.name starfire-bot
          git config user.email 83063940+starfire-bot@users.noreply.github.com

      - name: Starfire bot
        if: contains(fromJson('["XNXKTech", "StarUbiquitous"]'), github.event.repository.owner.name) == false
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit changes
        continue-on-error: true
        run: |
          git add .
          git commit -m "style: fix typo [skip ci]"
          git push origin ${{ github.head_ref }}
