name: Code style analysis

on:
  workflow_call:
    inputs:
      runs-on:
        default: "['ubuntu-latest']"
        description: The OSs that the workflow is run on
        required: false
        type: string
      php-versions:
        default: '8.0'
        required: false
        type: string
      version:
        description: 'Stringified JSON object listing target PHP versions'
        default: "['8.0']"
        required: false
        type: string
      stability:
        default: "['prefer-stable']"
        required: false
        type: string
    secrets:
      CI_PAT:
        required: false
      GH_TOKEN:
        description: 'Personal access token passed from the caller workflow'
        required: false

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN == '' && secrets.CI_PAT || secrets.GH_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN == '' && secrets.CI_PAT || secrets.GH_TOKEN }}
  token: ${{ secrets.GH_TOKEN == '' && secrets.CI_PAT || secrets.GH_TOKEN }}

jobs:
  ci:

    name: ${{ matrix.php }} - ${{ matrix.stability }}

    if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ${{ fromJson(inputs.runs-on) }}
        php: ${{fromJson(inputs.version)}}
        stability: ${{fromJson(inputs.stability)}}

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}
          token: ${{ env.GITHUB_TOKEN }}

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip
          coverage: none
          tools: php-cs-fixer, composer:v2, cs2pr

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3.0.8
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-php-${{ matrix.php }}-composer-

      - name: Use remote configuration
        if: contains(fromJson('["XNXKTech", "StarUbiquitous"]'), github.event.repository.owner.name) == true
        run: |
          wget -qO- https://raw.githubusercontent.com/XNXKTech/workflows/main/phpcs/.php-cs-fixer.php > .php-cs-fixer.php

      - name: PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: -v

      - name: Starfire bot
        if: contains(fromJson('["XNXKTech", "StarUbiquitous"]'), github.event.repository.owner.name) == true
        run: |
          git config user.name starfire-bot
          git config user.email 83063940+starfire-bot@users.noreply.github.com

      - name: Starfire bot
        if: contains(fromJson('["XNXKTech", "StarUbiquitous"]'), github.event.repository.owner.name) == false
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit changes
        continue-on-error: true
        run: |
          git add .
          git commit -m "style: fix typo [skip ci]"
          git push origin ${{ github.head_ref }} --force
