name: Laravel Insights

on:
  workflow_call:
    inputs:
      runs-on:
        default: "['ubuntu-latest']"
        description: The OSs that the workflow is run on
        required: false
        type: string
      versions:
        description: 'Stringified JSON object listing target PHP versions'
        default: "['8.0']"
        required: false
        type: string
      stability:
        default: "['prefer-stable']"
        required: false
        type: string
      extensions:
        description: 'List of PHP extensions to install'
        default: 'dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, memcached, gmp'
        required: false
        type: string
      coverage:
        description: 'Enable PHP code coverage'
        default: 'xdebug'
        required: false
        type: string
      tools:
        description: 'List of tools to install'
        default: 'php-cs-fixer, phpunit'
        required: false
        type: string
      composer_version:
        description: 'Version of Composer to use'
        default: 'v2'
        required: false
        type: string
      cache-key:
        description: 'Cache key to use for caching'
        default: 'cache-v1'
        required: false
        type: string
      min_quality:
        default: 80
        required: false
        type: number
      min_complexity:
        default: 80
        required: false
        type: number
      min_architecture:
        default: 65
        required: false
        type: number
      min_style:
        default: 80
        required: false
        type: number

jobs:
  ci:
    name: ${{ matrix.php-versions }} - ${{ matrix.stability }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ${{ fromJson(inputs.runs-on) }}
        php-versions: ${{fromJson(inputs.versions)}}
        stability: ${{fromJson(inputs.stability)}}

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 1

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ inputs.extensions }}
          key: ${{ inputs.cache-key }}

      - name: Cache extensions
        uses: actions/cache@v3.3.0
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ inputs.extensions }}
          coverage: ${{ inputs.coverage }}
          tools: ${{ inputs.tools }}, composer:${{ inputs.composer_version }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3.3.0
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-php-${{ matrix.php }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --optimize-autoloader

      - name: phpinsights
        run: |
          vendor/bin/phpinsights -n --ansi --min-quality=${{ inputs.min_quality }} --min-complexity=${{ inputs.min_complexity }} --min-architecture=${{ inputs.min_architecture }} --min-style=${{ inputs.min_style }} --format=github-action
