name: Python lint

on:
  workflow_call:
    inputs:
      versions:
        default: "3.8"
        description: 'The version of python to use'
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  token: ${{ secrets.GH_TOKEN }}

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 1

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Install pipenv
        run: pipx install pipenv

      - name: Setup Python ${{ inputs.versions }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.versions }}

      - name: Install pipenv
        run: |
          python -m pip install --upgrade flake8

      - id: cache-pipenv
        uses: actions/cache@v3.2.1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Run linters
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ env.GH_TOKEN }}
        run: |
          reviewdog -reporter="github-pr-review" -runners="flake8" -tee
