name: Python check format

on:
  workflow_call:
    inputs:
      versions:
        default: "3.8"
        description: 'The version of python to use'
        required: false
        type: string

jobs:
  check-format:
    name: Check formatting

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 1

      - name: Install pipenv
        run: pipx install pipenv

      - name: Setup Python ${{ inputs.versions }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.versions }}

      - name: Install pipenv
        run: |
          python -m pip install --upgrade black

      - id: cache-pipenv
        uses: actions/cache@v3.2.1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Run test suite
        run: |
          pipenv run test -v
