name: Rust tests

on:
  workflow_call:
    inputs:
      versions:
        default: "['stable']"
        description: 'The version of rustfmt to use'
        required: false
        type: string

jobs:
  tests:
    name: 'Tests'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        versions: ${{ fromJson(inputs.versions) }}

    steps:
      - uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 1

      - name: Setup Rust ${{ matrix.rust }}
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.versions }}

      - uses: Swatinem/rust-cache@v2

      - run: cargo test --verbose --workspace --all-features

