name: Rust check

on:
  workflow_call:
    inputs:
      versions:
        default: "['stable']"
        description: 'The version of rustfmt to use'
        required: false
        type: string

jobs:
  check:
    name: 'Check'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        versions: ${{ fromJson(inputs.versions) }}

    steps:
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 1

      - name: Setup Rust ${{ matrix.versions }}
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.versions }}

      - uses: Swatinem/rust-cache@v2

      - run: cargo check --verbose --workspace --all-features

